run_params:
  experiment_name: test2
  workdir: test
  trained_model: test1_latest.pth

#TODO add nested config & 
algorithm: 
  workdir: test
  name: n2v
  #List of class names from losses.py or pytorch
  loss: [n2v]
  # Pixel masking strategy #TODO add better description
  pixel_manipulation: n2v
  # Number of pixels to mask. Default is patch size ** number of patch dims / 32
  mask_pixel_percentage: 0.2
  #Class name from models.py
  model: UNET
  #Whether to use 2D or 3D convolutions #TODO better name ?
  conv_dims: 2
  depth: 2
  num_filter_base: 96

training:
  num_epochs: 500
  optimizer:
    #Name of the optimizer class from torch.optim
    name: Adam
    parameters:
      lr: 0.0004
  lr_scheduler: 
    #Name of the scheduler class from torch.optim.lr_scheduler
    name: ReduceLROnPlateau
    parameters:
      mode: min
      factor: 0.5
      patience: 30
      verbose: true
      threshold: 0.0001
      threshold_mode: rel
      cooldown: 0
      min_lr: 0
  # Toggles automatic mixed precision training
  amp: 
    use: false
    # Scaling parameter for mixed precision training. Power of 2 recommended
    init_scale: 1024
  max_grad_norm: 0
  running_stats: false
  data:
    #Path to the data
    path: data/BSD68_reproducibility/BSD68_reproducibility_data/train
    # File type to load
    ext: &EXT npy
    axes: &AX SYX
    #Number of files to read. Read all if None
    num_files: Null
    # Patch generation strategy [random, sequential]
    extraction_strategy: random
    #Patch shape in (z)yx. 2D or 3D
    patch_size: &PS [64, 64]
    # Batch size
    batch_size: 128
    #Num workers parameter for data loader
    num_workers: 0
    #TODO add list of specific augmentations or func/list of funcs 
  augmentation: basic
  

evaluation:
  data:
    #Path to the data
    path: data/BSD68_reproducibility/BSD68_reproducibility_data/val
    # File type to load
    ext: *EXT
    axes: *AX
    #Number of files to read. Read all if None
    num_files: Null
    # Patch generation strategy [random, sequential]
    extraction_strategy: sequential
    #Patch shape in (z)yx. 2D or 3D
    patch_size: *PS
    #Total number of patches to generate. Only applicable for random patching
    num_patches: Null
    # Batch size
    batch_size: 1
    #Num workers parameter for data loader
    num_workers: 0
    batch_size: 1
    num_workers: 0
    augmentation: Null
  metric: psnr


prediction:
  data:
    #Path to the data
    path: data/BSD68_reproducibility/BSD68_reproducibility_data/test
    # File type to load
    ext: *EXT
    axes: SYX
    #Number of files to read. Read all if None
    num_files: Null
    # Patch generation strategy [random, sequential]
    extraction_strategy: predict
    #Patch shape in (z)yx. 2D or 3D
    patch_size: [64, 64]
    # Batch size
    batch_size: 1
    #Num workers parameter for data loader
    num_workers: 0
    #test-time augmentation
    tta: Null
  #Tuple of overlap values for each dimension between patches in pixels (should be half of the network receptive field)
  overlap: [48, 48] 
  metric: psnr

#TODO rename to logging? Move to run params?
misc:
  use_wandb: Null